version: 2
updates:
  - package-ecosystem: 'npm'
    directory: ''
    open-pull-requests-limit: 1
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'America/Chicago'
    ignore:
      - dependency-name: 'tfx-cli'
    labels:
      - 'dependencies'
      - 'extension'
    assignees:
      - 'charleszipp'
    reviewers:
      - 'charleszipp'

  - package-ecosystem: 'npm'
    directory: 'tasks/terraform-cli'
    open-pull-requests-limit: 1
    schedule:
      interval: 'daily'
      time: '05:30'
      timezone: 'America/Chicago'
    ignore:
      - dependency-name: 'tfx-cli'
    labels:
      - 'dependencies'
      - 'terraform-cli-task'
    assignees:
      - 'charleszipp'
    reviewers:
      - 'charleszipp'

  - package-ecosystem: 'npm'
    directory: 'tasks/terraform-installer'
    open-pull-requests-limit: 1
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'America/Chicago'
    ignore:
      - dependency-name: 'tfx-cli'
    labels:
      - 'dependencies'
      - 'terraform-installer-task'
    assignees:
      - 'charleszipp'
    reviewers:
      - 'charleszipp'

  - package-ecosystem: 'npm'
    directory: 'views/terraform-plan'
    open-pull-requests-limit: 1
    schedule:
      interval: 'daily'
      time: '06:30'
      timezone: 'America/Chicago'
    ignore:
      - dependency-name: 'tfx-cli'
    labels:
      - 'dependencies'
      - 'terraform-plan-view'
    assignees:
      - 'charleszipp'
    reviewers:
      - 'charleszipp'

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
