parameters:
  - name: instance
    type: string
  - name: workingDir
    type: string
  - name: runTests
    type: boolean
    default: "false"

jobs:
  - job: ${{ parameters.instance }}_terraform_cli
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/terraform-cli
          runTests: ${{ parameters.runTests }}