parameters:
  - name: instance
    type: string
  - name: workingDir
    type: string

jobs:
  - job: ${{ parameters.instance }}_terraform_cli
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/tasks/terraform-cli
          artifact: ${{ parameters.instance }}_terraform_cli
          runTests: true

  - job: ${{ parameters.instance }}_terraform_installer
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/tasks/terraform-installer
          artifact: ${{ parameters.instance }}_terraform_installer

  - job: ${{ parameters.instance }}_terraform_plan
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/views/terraform-plan
          artifact: ${{ parameters.instance }}_terraform_plan

      # Unfortunately, terraform plan view needs some work to have it complay with test_npm.yml so we hard code the steps for now
      - task: Npm@1
        displayName: test
        inputs:
          workingDir: ${{ parameters.workingDir }}/views/terraform-plan
          command: custom
          customCommand: run test
      - task: PublishTestResults@2
        displayName: test - publish results
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: 'results.xml'
          searchFolder: ${{ parameters.workingDir }}/views/terraform-plan/.tests


          