parameters:
  - name: instance
    type: string
  - name: workingDir
    type: string

jobs:
  - job: terraform_cli_${{ parameters.instance }}
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/tasks/terraform-cli
          artifact: ${{ parameters.instance }}_terraform_cli
          runTests: true

  - job: terraform_installer_${{ parameters.instance }}
    steps:
      - template: build_npm.yml
        parameters:
          workingDir: ${{ parameters.workingDir }}/tasks/terraform-installer
          artifact: ${{ parameters.instance }}_terraform_installer


          