parameters:
  - name: jobName
    type: string
  - name: dependsOn
    type: object
    default:
      - version
  - name: workingDir
    type: string
  - name: runTests
    type: boolean
    default: false

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  variables:
      GitVersion.SemVer: $[ dependencies.version.outputs['version.GitVersion.SemVer'] ]
      GitVersion.Major: $[ dependencies.version.outputs['version.GitVersion.Major'] ]
      GitVersion.Minor: $[ dependencies.version.outputs['version.GitVersion.Minor'] ]
      GitVersion.Patch: $[ dependencies.version.outputs['version.GitVersion.Patch'] ]
  steps:
    - task: Npm@1
      displayName: version
      inputs:
        workingDir: ${{ parameters.workingDir }}
        command: custom
        customCommand: version $(GitVersion.SemVer) --no-git-tag-version --allow-same-version
    - task: Npm@1
      displayName: install  
      inputs:
        workingDir: ${{ parameters.workingDir }}
        command: ci
    - task: Npm@1
      displayName: build
      inputs:            
        workingDir: ${{ parameters.workingDir }}
        command: custom
        customCommand: run build
    - ${{ if eq(parameters.dependsOn, true) }}:
      - template: test_npm.yml
        inputs:
          workingDir: ${{ parameters.workingDir }}
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: version tasks
      inputs:
        targetFiles: ${{ parameters.workingDir }}/task.json
        escapeType: none
    - task: Npm@1
      displayName: pack
      inputs:  
        workingDir: ${{ parameters.workingDir }}
        command: custom
        customCommand: run pack
    - task: CopyFiles@2
      displayName: stage artifacts
      inputs:
        contents: |
          tasks/terraform-cli/.dist/**/*
        targetFolder: $(Build.ArtifactStagingDirectory)
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: terraform_cli
      displayName: publish artifacts