parameters:
  - name: scenarios
    type: object
    default: []
  - taskVersions:
    type: object
    default: [2]

stages:
- ${{ each taskVersion in parameters.taskVersions }}:
  - stage: test_${{ taskVersion }}
    variables:
      - group: env_rc
      - name: backendAzureRmResourceGroupName
        value: rg-trfrm-rc-chn-jbj
      - name: backendAzureRmResourceGroupLocation
        value: switzerlandnorth
      - name: backendAzureRmStorageAccountName
        value: sttrfrmrcchnjbj
      - name: backendAzureRmStorageAccountSku
        value: Standard_RAGRS
      - name: backendAzureRmContainerName
        value: azure-pipelines-terraform
    jobs:
      - ${{ each scenario in parameters.scenarios }}:
        - template: ${{ scenario }}
          inputs:
            taskVersion: ${{ taskVersion }}