pr: none
trigger:
  batch: true
  branches:
    include: 
      - main
  tags:
    exclude: 
      - '*'
  paths:
    exclude: 
      - '**/*.md'
      - '**/*.(jpg|jpeg|png)'
      - '**/*.tf'
      - '**/*.env'
      - '**/*.vars'        
      - '_test-agent/*'
      - '.vscode/*'
      - 'screenshots/*'
      - 'templates/*'
      - 'LICENSE'    
  
variables:
  terraform_extension_dir: $(System.DefaultWorkingDirectory)
  terraform_installer_dir: $(System.DefaultWorkingDirectory)/tasks/terraform-installer
  terraform_cli_dir: $(System.DefaultWorkingDirectory)/tasks/terraform-cli
  views_terraform_plan_dir: $(System.DefaultWorkingDirectory)/views/terraform-plan
  terraform_templates_dir: $(System.DefaultWorkingDirectory)/templates
  # secure files can only be parameterized if variable is defined at global scope
  # https://github.com/microsoft/azure-pipelines-tasks/issues/6885#issuecomment-618200608
  tf_variables_secure_file: 4a0c36e2-bb51-41ed-87b1-2e668c64bb69
  marketplace_publisher: JasonBJohnson
  ado_service_url: https://dev.azure.com/azure-pipelines-terraform-rc

pool:
  vmImage: ubuntu-latest

name: $(GitVersion.FullSemVer)

stages:
  - template: build/build.yml
    parameters:
      stage: rc
  - template: publish/publish_private.yml
    parameters:
      stage: rc
  - template: test/test.yml
    parameters:
      stage: rc
      scenarios:
        - smoke_test.yml
        - publish_plan_results.yml
        - plan_with_command_options_var_file.yml
        - local_exec_az_cli.yml
        - init_with_ensure_backend_no_storage_account.yml
        - init_with_self_configured_backend.yml
        - switch_workspaces.yml
        # - aws_self_configured.yml
        # - aws_service_connection.yml
        - init_without_ensure_backend.yml
        # - gcp_credential_file.yml
        # - azurerm_mgmt_group_service_connection.yml       # will need another subscription to do this one
        - state_commands.yml
