trigger: none
pr: 
  autoCancel: true
  drafts: false
  branches:
    include: 
      - main
  paths:
    exclude: 
      - '**/*.md'
      - '**/*.(jpg|jpeg|png)'
      - '**/*.tf'
      - '**/*.env'
      - '**/*.vars'        
      - '_test-agent/*'
      - '.vscode/*'
      - 'screenshots/*'
      - 'templates/*'
      - 'LICENSE'
  

variables:
  terraform_extension_dir: $(System.DefaultWorkingDirectory)
  terraform_installer_dir: $(System.DefaultWorkingDirectory)/tasks/terraform-installer
  terraform_cli_dir: $(System.DefaultWorkingDirectory)/tasks/terraform-cli
  views_terraform_plan_dir: $(System.DefaultWorkingDirectory)/views/terraform-plan
  terraform_templates_dir: $(System.DefaultWorkingDirectory)/templates
  # secure files can only be parameterized if variable is defined at global scope
  # https://github.com/microsoft/azure-pipelines-tasks/issues/6885#issuecomment-618200608
  tf_variables_secure_file: 64600c10-6c26-4008-8863-652524d03f1e
  marketplace_publisher: charleszipp
  ado_service_url: https://dev.azure.com/azure-pipelines-terraform-beta


name: $(GitVersion.FullSemVer)

stages:
  - template: build/build.yml
    parameters:
      stage: beta
  - template: publish/publish_private.yml
    parameters:
      stage: beta
  - template: test/test.yml
    parameters:
      stage: beta
      scenarios:
        - smoke_test.yml
        - publish_plan_results.yml
        - plan_with_command_options_var_file.yml
        - local_exec_az_cli.yml
        - init_with_ensure_backend_no_storage_account.yml
        - init_with_self_configured_backend.yml
        - switch_workspaces.yml        
        # removing for now as it appears the compatible azurerm plugin is no longer available
        # - init_with_version_11.yml
