trigger: none
pr: none

resources:
  pipelines:
  - pipeline: main
    source: main
    trigger: true

variables:
  tf_variables_secure_file: 4a0c36e2-bb51-41ed-87b1-2e668c64bb69
  terraform_templates_dir: $(System.DefaultWorkingDirectory)/templates
  terraformVersion: 1.0.10

stages:
- template: templates/integration_tests.yml
  parameters:
    scenarios:
      - test/smoke_test.yml
      - test/publish_plan_results.yml
      - test/plan_with_command_options_var_file.yml
      - test/local_exec_az_cli.yml
      - test/init_with_ensure_backend_no_storage_account.yml
      - test/init_with_self_configured_backend.yml
      - test/switch_workspaces.yml
      # - test/aws_self_configured.yml
      # - test/aws_service_connection.yml
      - test/init_without_ensure_backend.yml
      # - test/gcp_credential_file.yml
      # - test/azurerm_mgmt_group_service_connection.yml       # will need another subscription to do this one
      - test/state_commands.yml