trigger: none
pr: none

resources:
  pipelines:
  - pipeline: main
    source: main
    branch: package-versions-2
    trigger:
      branches:
      - '*'

steps:
- bash: echo "test runs after main completes"